# Embedding Validation

This notebook tests the `ESMEmbedder` from `embedder.py`

In [1]:
import pandas as pd
import numpy as np
import os
import sys

from embedder import ESMEmbedder

processor = ESMEmbedder()

/Users/ryanfue/.virtualenvs/iGEM_Claremont/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 534/534 [00:00<00:00, 16565.40it/s]
[transformers] EsmModel LOAD REPORT from: facebook/esm2_t33_650M_UR50D
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
lm_head.layer_norm.bias   | UNEXPECTED |
pooler.dense.weight       | MISSING    |
pooler.dense.bias         | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [2]:
# Load data

data_path = "../01_data_ground_truth/inputs/complete_phage_data_Pseudomonas.csv"

df = pd.read_csv(data_path,nrows = 15,usecols=['full_sequence'])
df

                                        full_sequence
0   CGGACGAAAGGCGGCATGATTGCTTAAGGAGATTTTCATGGCAAGT...
1   GTGGGTGAGGATCGAATCGGCGGTTGATGGGCGACGATGGTGGTGA...
2   ATGAATCTGTCTTCCAGAAATTCAAATAATTGTTCAAAAAGTGCTT...
3   TCTACTTGATATTCGCAATTATTGGGATGTAAAACCATTTGCTTAC...
4   ACTGAACCACGCCAACGAAACCATCTGAGCCGGCTTACCGCCATTT...
5   GCTCTTTTCTCATTTCCACAGAATTTAGGTTTCAAGATGGCACGAC...
6   ATGTTCAAGCTCAATCCTGCACTGCGAGCGGTCTGGCGAACTCGTG...
7   ATGTTCAAGCTCAATCCTGCACTGCGAGCGGTCTGGCGAACTCGTG...
8   CGCCTTCTGCAAGACGTGCCTCTCGCTTGTGGTCTGCACGGGTCAT...
9   ATGATCCATAAGGCATTGAACACCCTCCTACAAGCAGCAGGTGCAA...
10  GTTATAAAGGCCCTTACGGGCCTATTTTGTTAATCTGCAACCTTCT...
11  CGAAAATCTATCAACTTCCCATAATACAACGCCTTCACCCAACCCT...
12  CGCTGTTCTCGTTTGCGTTCGCTGCTGACAGAACGAACTTTATAGA...
13  GTCGTCTAACTCGCTTGCTGTTTGCTGCTGACAGAACGAACTTTAT...
14  ATGACTGATATTAAAACCATTCCCGGTATTGACAACGCTAAACTCA...

In [3]:
embedded_df = processor.proccess_dataframe(df, "full_sequence")
embedded_df

Processing 15 sequences in batches of 4...

100%|██████████| 4/4 [00:42<00:00, 10.61s/it]

,full_sequence,embeddings
0,CGGACGAAAGGCGGCATGATTGCTTAAGGAGATTTTCATGGCAAGT...,"[-0.24153273, -0.078051046, 0.03998271, 0.1890..."
1,GTGGGTGAGGATCGAATCGGCGGTTGATGGGCGACGATGGTGGTGA...,"[-0.22551574, -0.07853979, 0.029299354, 0.1844..."
2,ATGAATCTGTCTTCCAGAAATTCAAATAATTGTTCAAAAAGTGCTT...,"[-0.24420647, -0.10198477, 0.009790982, 0.2114..."
3,TCTACTTGATATTCGCAATTATTGGGATGTAAAACCATTTGCTTAC...,"[-0.24335109, -0.06006592, 0.009002643, 0.2373..."
4,ACTGAACCACGCCAACGAAACCATCTGAGCCGGCTTACCGCCATTT...,"[-0.23716818, -0.0779652, 0.026950013, 0.19451..."
5,GCTCTTTTCTCATTTCCACAGAATTTAGGTTTCAAGATGGCACGAC...,"[-0.24070838, -0.07919489, 0.024551308, 0.1941..."
6,ATGTTCAAGCTCAATCCTGCACTGCGAGCGGTCTGGCGAACTCGTG...,"[-0.24397756, -0.084106416, 0.020711351, 0.194..."
7,ATGTTCAAGCTCAATCCTGCACTGCGAGCGGTCTGGCGAACTCGTG...,"[-0.24397755, -0.084106386, 0.020711359, 0.194..."
8,CGCCTTCTGCAAGACGTGCCTCTCGCTTGTGGTCTGCACGGGTCAT...,"[-0.22264647, -0.03887223, 0.040170494, 0.1909..."
9,ATGATCCATAAGGCATTGAACACCCTCCTACAAGCAGCAGGTGCAA...,"[-0.2339367, -0.080711395, 0.012869387, 0.1861..."
10,GTTATAAAGGCCCTTACGGGCCTATTTTGTTAATCTGCAACCTTCT...,"[-0.23215039, -0.07413537, 0.014915244, 0.1963..."
11,CGAAAATCTATCAACTTCCCATAATACAACGCCTTCACCCAACCCT...,"[-0.22647633, -0.04597822, 0.036209658, 0.2012..."
12,CGCTGTTCTCGTTTGCGTTCGCTGCTGACAGAACGAACTTTATAGA...,"[-0.23441488, -0.060166113, 0.03190068, 0.2003..."
13,GTCGTCTAACTCGCTTGCTGTTTGCTGCTGACAGAACGAACTTTAT...,"[-0.24725467, -0.09790756, 0.0015134946, 0.213..."
14,ATGACTGATATTAAAACCATTCCCGGTATTGACAACGCTAAACTCA...,"[-0.23491749, -0.073283516, 0.007847341, 0.241..."